/**
 * AI Assistant Services Index
 * Central export point for all AI assistant services
 */

export * from './model-management-service';

// User Preference Manager - export with aliases to avoid conflicts
export {
  UserPreferenceManager,
  IUserPreferenceManager,
  UsagePatternAnalysis,
  ModelUsagePattern,
  TaskTypeDistribution,
  TimeUsagePattern,
  PerformancePreference,
  CostSensitivity,
  OptimizationOpportunity,
  PreferenceChange,
  UserCostAnalytics,
  ModelCostBreakdown,
  TaskTypeCostBreakdown,
  TimeCostBreakdown,
  CostTrendData,
  BudgetUtilization,
  UtilizationMetric,
  CostEfficiencyMetrics,
  CostOptimizationSuggestion,
  BudgetRecommendation as UserBudgetRecommendation,
  CostRecommendation as UserCostRecommendation,
  TimeRange as UserTimeRange
} from './user-preference-manager';

// Model Cost Calculator - export with aliases to avoid conflicts  
export {
  ModelCostCalculator,
  IModelCostCalculator,
  CostEstimationRequest,
  CostEstimation,
  TaskCostEstimation,
  BatchCostRequest,
  BatchCostEstimation,
  DynamicPricing,
  PricingContext,
  SurgePricing,
  DemandMetrics,
  ImageSize,
  QualityLevel,
  RequestPriority,
  CostBreakdown,
  FeatureCost,
  CostFactor,
  CostFactorType,
  AlternativeCostOption,
  CostRange,
  ModelCostComparison,
  CostRecommendation as ModelCostRecommendation,
  BudgetImpact,
  BudgetPercentage,
  BatchCostBreakdown,
  PricingAdjustment,
  AdjustmentType,
  UserTier,
  SurgeReason,
  AlternativeModel,
  BudgetValidationResult,
  RemainingBudget,
  BudgetViolation,
  BudgetViolationType,
  ViolationSeverity,
  BudgetRecommendation as CostBudgetRecommendation,
  BudgetAction,
  ActionPriority,
  BudgetConstraintResult,
  ConstraintCheck,
  BudgetConstraint,
  BudgetConstraintType,
  TimePeriod,
  ConstraintStatus,
  BudgetReservation,
  ReservationStatus,
  UsageMetrics,
  CostAlert,
  AlertType,
  AlertSeverity,
  CostThreshold,
  ThresholdType,
  CostOptimizationResult,
  ModelAlternative,
  OptimizationReasoning,
  UsagePattern,
  ModelUsageStats,
  TaskUsageStats,
  PeakUsage,
  TimeRange as CostTimeRange,
  CostReductionSuggestion,
  ReductionType,
  EffortLevel,
  ImpactLevel,
  UsageProjection,
  ProjectedUsage,
  ROIAnalysis,
  ModelROI,
  ROIComparison,
  ROIRecommendation,
  ROIAction
} from './model-cost-calculator';